// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW_cz12hgG7arTvFVIlu3oPQ4neRVqheo',
    appId: '1:848385938429:web:c75d7b742cabfdd9257f94',
    messagingSenderId: '848385938429',
    projectId: 'calc-app-351c7',
    authDomain: 'calc-app-351c7.firebaseapp.com',
    storageBucket: 'calc-app-351c7.appspot.com',
    measurementId: 'G-WYNSTKCWKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP7gv_hQXEWQqq6MlUCoMS-u2PriCBkFs',
    appId: '1:848385938429:android:817907cd4db7eb08257f94',
    messagingSenderId: '848385938429',
    projectId: 'calc-app-351c7',
    storageBucket: 'calc-app-351c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCffucYUWTbu9J9pHYhTD_oJ2Y1HGB5nPE',
    appId: '1:848385938429:ios:ae6c78405d9a86d5257f94',
    messagingSenderId: '848385938429',
    projectId: 'calc-app-351c7',
    storageBucket: 'calc-app-351c7.appspot.com',
    iosBundleId: 'com.example.calculatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCffucYUWTbu9J9pHYhTD_oJ2Y1HGB5nPE',
    appId: '1:848385938429:ios:ae6c78405d9a86d5257f94',
    messagingSenderId: '848385938429',
    projectId: 'calc-app-351c7',
    storageBucket: 'calc-app-351c7.appspot.com',
    iosBundleId: 'com.example.calculatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW_cz12hgG7arTvFVIlu3oPQ4neRVqheo',
    appId: '1:848385938429:web:7824e670949684ce257f94',
    messagingSenderId: '848385938429',
    projectId: 'calc-app-351c7',
    authDomain: 'calc-app-351c7.firebaseapp.com',
    storageBucket: 'calc-app-351c7.appspot.com',
    measurementId: 'G-Q1X99J2MLV',
  );

}